id: P3BB5B2BA
initial_creation_type: input
source_metadata:
  title: Lochen Chönyi Zangmo
  language: bo
  description: 'Texts by and about Jetsün Lochen Chönyi Zangmo (lo chen chos nyid
    bzang mo, 1853/1865–1950/1951) of Shukseb (shug gseb), one of the most celebrated
    yoginīs of the last century:'
  volume:
    3b72655d83d54be88c680ea7c54c5d06:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      parent: Guru Yoga
    19a2e9ce4c88473eb7b87e3f1f7fc5b8:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      parent: Long Life Prayers
created_at: '2022-03-01T00:38:09.278754'
last_modified_at: '2022-03-01T00:38:09.278757'
statistics:
  total_words: 664
  total_non_words: 73
quality:
  non_words_ratio: 0.11
